
# This is the config file for your Supabase project's API services.
# The environment variables configured here will be available in the SQL on database startup.
project_id = "rehadpogugijylybwmoe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[storage]
enabled = true

[functions]
[functions.storage-manager]
verify_jwt = false
