
project_id = "rehadpogugijylybwmoe"

[api]
# Port to use for the API URL
port = 54321
scheme = "http"

[db]
# Port to use when connecting to the database
port = 54322

[studio]
# Port to use for Supabase Studio
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - the
# inbox server is used to catch the emails and display them for testing purposes.
[inbucket]
# Port to use for the email inbox server
port = 54324

[storage]
# The maximum file size allowed to be uploaded to storage when using the Storage API (in bytes)
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allowlist for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refreshing of tokens prior to expiry.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Configure one of the supported storage providers.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# For apple signin in native apps or in the browser on MacOS/iOS
# e.g. io.supabase.myapp://auth/callback
native_redirect_uri = ""
# e.g. ["name", "email"]
scopes = ["name", "email"]

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["openid", "profile", "email", "offline_access"]
scopes = ["openid", "profile", "email", "offline_access"]

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["account", "repository"]
scopes = ["account", "repository"]

[auth.external.discord]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["identify", "email"]
scopes = ["identify", "email"]

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["email", "photos", "user_friends"]
scopes = ["email", "photos", "user_friends"]

[auth.external.figma]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["file_read", "user"]
scopes = ["file_read", "user"]

[auth.external.github]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["user:email", "read:user"]
scopes = ["user:email", "read:user"]

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
url = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["read_user"]
scopes = ["read_user"]

[auth.external.google]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["email", "profile"]
scopes = ["email", "profile"]

[auth.external.kakao]
enabled = false
client_id = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
scope = "profile_nickname profile_image account_email"

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["r_liteprofile", "r_emailaddress"]
scopes = ["r_liteprofile", "r_emailaddress"]

[auth.external.notion]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. [] (Look at notion docs for more details about scopes: https://developers.notion.com/docs/authorization#scopes)
scopes = []

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["openid", "user:read:email"]
scopes = ["openid", "user:read:email"]

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["user-read-email"]
scopes = ["user-read-email"]

[auth.external.slack]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. [] (Look at Slack docs for more details about scopes: https://api.slack.com/legacy/oauth-scopes)
scopes = []

[auth.external.workos]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# The connection ID is from WorkOS dashboard
connection = ""
# The provider is what you want to use for authentication
provider = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# e.g. ["user:read", "meeting:read", "meeting:write"]
scopes = ["user:read", "meeting:read", "meeting:write"]

[functions.storage-manager]
verify_jwt = false
