
project_id = "rehadpogugijylybwmoe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[db.shadow]
port = 54320

[studio]
enabled = true
port = 54323

[auth]
enabled = true
port = 54324

[realtime]
enabled = true
port = 54325

[storage]
enabled = true
port = 54326

[analytics]
enabled = false
port = 54327

[inbucket]
enabled = true
port = 54328

[functions.admin-setup]
verify_jwt = false

[functions.ai-query]
verify_jwt = false

[functions.storage-manager]
verify_jwt = false

[functions.transform]
verify_jwt = false

[functions.data-processor]
verify_jwt = false
